name: boilerplate_flutter
description: Boilerplate mobile app by Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  repository:
    path: ./repository
  common:
    path: ./common

  cupertino_icons: ^0.1.2
  rxdart: ^0.26.0
  equatable: ^1.2.5
  flutter_bloc: ^7.0.1
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  firebase_core: ^1.2.0
  firebase_analytics: ^8.1.0
  firebase_messaging: ^10.0.0
  firebase_crashlytics: ^2.0.4
  firebase_auth: ^1.2.0
  progress_indicators: ^1.0.0
  sprintf: ^4.0.2
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.4
  connectivity: ^3.0.6
  flutter_dotenv: ^2.1.0
  flutter_udid: ^1.0.1
  device_info: ^2.0.2
  just_audio: ^0.7.5
  package_info: ^2.0.2
  google_sign_in: ^4.1.4
  loadmore: ^1.0.4
  app_review: ^2.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.8
  bloc_test: ^8.0.1
  pedantic: ^1.9.0 # Analysis
  mockito: ^4.1.1 # Testing

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:     
    - assets/
    - assets/icons/
    - assets/images/
    - assets/sounds/
    - lib/i18n/
    - .env
    - test_data/
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
module:
  androidX: true